FROM ffosilva/sgx:sgx_2.11

# Install dependencies
RUN apt-get update && \
    apt-get install -y g++

# COPY . ./
RUN cp -rf /opt/intel/sgxsdk/SampleCode/SampleEnclave/* .

RUN make SGX_DEBUG=0 SGX_PRERELEASE=1 SGX_MODE=HW

CMD ["./app"]
